### ISSUE TITLE
MissingModException ccBGSSSE001-Fish.esm

### ISSUE THREAD

**Issue by doxxx** [Excinerus/AI-Overhaul-Patcher#14]
Hi,

The patcher is failing with a MissingModException for ccBGSSSE001-Fish.esm. The patcher worked earlier today when I first ran it after installing AI Overhaul. But now after I installed a few other mods (Simple Horses SE, Horses Simply Turn Better) and disabled some others (Convenient Horses), the patcher is failing.

I tried disabling the additional mods that I installed but the patcher still fails.

I don't really understand how this error could occur. The master file it's referencing can't be disabled. LOOT is not showing any errors in the plugin list.

Here's the full log for the run:

```
Compiling
No extra data to consider
("C:\Users\Gordon\AppData\Local\Temp\Synthesis\ie0l3udo.ncs\Git\ro22k4ha.2rk\Runner\AIOverhaulPatcher"): "dotnet" "build \"AIOverhaulPatcher.csproj\" --runtime win-x64 -c Release"
Compiled
Sha "224bc74e965757271ac3f302a8836c7886091ff7"
Running
(""): "dotnet" "run --project \"C:\Users\Gordon\AppData\Local\Temp\Synthesis\ie0l3udo.ncs\Git\ro22k4ha.2rk\Runner\AIOverhaulPatcher\AIOverhaulPatcher.csproj\" --runtime win-x64 -c Release --no-build run-patcher --DataFolderPath \"C:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\" --ExtraDataFolder \"D:\Games\SkyrimTools\Synthesis\Data\Skyrim Special Edition\AI-Overhaul-Patcher\" --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\Gordon\AppData\Local\Temp\Synthesis\ie0l3udo.ncs\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath \"C:\Users\Gordon\AppData\Local\Temp\Synthesis\ie0l3udo.ncs\Workspace\Synthesis\1 - AI-Overhaul-Patcher\Synthesis.esp\" --PatcherName AI-Overhaul-Patcher"
Mutagen version: 0.36.3
Mutagen sha: fc2d89802dd42fe2558e6c754b35a130d7f2c09f
Synthesis version: 0.22.1
Synthesis sha: 820cdd4f57945993117de9613b154f002b930eeb
run-patcher --DataFolderPath "C:\Games\Steam\steamapps\common\Skyrim Special Edition\Data" --ExtraDataFolder "D:\Games\SkyrimTools\Synthesis\Data\Skyrim Special Edition\AI-Overhaul-Patcher" --GameRelease SkyrimSE --ModKey Synthesis.esp --LoadOrderFilePath C:\Users\Gordon\AppData\Local\Temp\Synthesis\ie0l3udo.ncs\Workspace\Synthesis\Plugins.txt --LoadOrderIncludesCreationClub --OutputPath "C:\Users\Gordon\AppData\Local\Temp\Synthesis\ie0l3udo.ncs\Workspace\Synthesis\1 - AI-Overhaul-Patcher\Synthesis.esp" --PatcherName AI-Overhaul-Patcher
Prepping state.
Language: English
Can use localization: True
Localized: False
Running patch.
Unofficial Skyrim Special Edition Patch.esp
at 5
0/424 Npcs
Reading settings: D:\Games\SkyrimTools\Synthesis\Data\Skyrim Special Edition\AI-Overhaul-Patcher\settings.json
10/424 Npcs
20/424 Npcs
30/424 Npcs
40/424 Npcs
50/424 Npcs
60/424 Npcs
70/424 Npcs
80/424 Npcs
90/424 Npcs
100/424 Npcs
110/424 Npcs
120/424 Npcs
130/424 Npcs
140/424 Npcs
150/424 Npcs
160/424 Npcs
170/424 Npcs
180/424 Npcs
190/424 Npcs
200/424 Npcs
210/424 Npcs
220/424 Npcs
230/424 Npcs
240/424 Npcs
250/424 Npcs
260/424 Npcs
270/424 Npcs
280/424 Npcs
290/424 Npcs
300/424 Npcs
310/424 Npcs
320/424 Npcs
330/424 Npcs
340/424 Npcs
350/424 Npcs
360/424 Npcs
370/424 Npcs
380/424 Npcs
390/424 Npcs
400/424 Npcs
410/424 Npcs
420/424 Npcs
Finished patch.
Writing to output: C:\Users\Gordon\AppData\Local\Temp\Synthesis\ie0l3udo.ncs\Workspace\Synthesis\1 - AI-Overhaul-Patcher\Synthesis.esp
MissingModException ccBGSSSE001-Fish.esm: A referenced mod was not present on the load order being sorted against: ccBGSSSE001-Fish.esm.  This mod was referenced by MajorRecord: 000B30:ccBGSSSE001-Fish.esm    at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.SortMasters(List`1 modKeys)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.ConstructWriteMasters(IModGetter mod)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.PostProcessAdjustments(MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader)
   at Mutagen.Bethesda.Plugins.Binary.Translations.ModHeaderWriteLogic.WriteHeader(BinaryWriteParameters param, MutagenWriter writer, IModGetter mod, IModHeaderCommon modHeader, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.Internals.SkyrimModCommon.WriteParallel(ISkyrimModGetter item, Stream stream, BinaryWriteParameters param, ParallelWriteParameters parallelParam, ModKey modKey)
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.WriteToBinaryParallel(ISkyrimModGetter item, String path, BinaryWriteParameters param, ParallelWriteParameters parallelParam, IFileSystem fileSystem)
   at Mutagen.Bethesda.Skyrim.SkyrimMod.Mutagen.Bethesda.Plugins.Records.IModGetter.WriteToBinaryParallel(FilePath path, BinaryWriteParameters param, IFileSystem fileSystem, ParallelWriteParameters parallelWriteParams)
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, Nullable`1 exportKey, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 562
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.Run(RunSynthesisMutagenPatcher args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 453
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass36_0.<<InternalRun>b__1>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\SynthesisPipeline.cs:line 416
Synthesis.Bethesda.Execution.CliUnsuccessfulRunException: Error running solution patcher
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRunner.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRunner.cs:line 52
   at Synthesis.Bethesda.Execution.Patchers.Running.Solution.SolutionPatcherRun.Run(RunSynthesisPatcher settings, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Patchers\Running\Solution\SolutionPatcherRun.cs:line 52
   at Synthesis.Bethesda.Execution.Running.Runner.RunAPatcher.Run(IGroupRun groupRun, PatcherPrepBundle prepBundle, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAPatcher.cs:line 65
   at Synthesis.Bethesda.Execution.Running.Runner.RunSomePatchers.Run(IGroupRun groupRun, PatcherPrepBundle[] patchers, CancellationToken cancellation, Nullable`1 sourcePath, RunParameters runParameters) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunSomePatchers.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.RunAGroup.Run(IGroupRun groupRun, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAGroup.cs:line 59
   at Synthesis.Bethesda.Execution.Running.Runner.RunAllGroups.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\RunAllGroups.cs:line 36
   at Synthesis.Bethesda.Execution.Running.Runner.ExecuteRun.Run(IGroupRun[] groups, CancellationToken cancellation, DirectoryPath outputDir, RunParameters runParameters, Nullable`1 sourcePath) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.Execution\Running\Runner\ExecuteRun.cs:line 54
   at Synthesis.Bethesda.GUI.Services.Profile.Running.ExecuteGuiRun.Run(IEnumerable`1 groupRuns, PersistenceMode persistenceMode, Boolean localize, Language targetLanguage, CancellationToken cancel) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\Services\Profile\Running\ExecuteGuiRun.cs:line 49
   at Synthesis.Bethesda.GUI.ViewModels.Profiles.Running.RunVm.<Run>b__39_1(Unit _) in D:\a\Synthesis\Synthesis\Synthesis.Bethesda.GUI\ViewModels\Profiles\Running\RunVm.cs:line 200
```

And here is my plugins.txt:

```
# This file was automatically generated by Mod Organizer.
*Unofficial Skyrim Special Edition Patch.esp
*Unofficial Rare Curios Patch.esl
*Unofficial Saints and Seducers Patch.esl
*Unofficial Skyrim Survival Patch.esl
*Unofficial Stalhrim Fur Armor Patch.esl
*RSkyrimChildren.esm
*FISS.esp
*AHZmoreHUDInventory.esl
*Expressive Facegen Morphs.esl
*Schlongs of Skyrim - Core.esm
*Improved Vanilla FaceGen.esp
*iWant Widgets.esl
*Experience.esl
*High Poly Head.esm
*ApachiiHairMales.esm
*Enhanced Landscapes.esp
*Landscape and Water Fixes.esp
*Occ_Skyrim_Tamriel.esp
*3DNPC.esp
*Lux - Resources.esp
*Lux Via.esp
*RealisticWaterTwo - Resources.esm
*Lux Orbis - Master plugin.esm
*Better Dynamic Snow SE - DisableRefs.esm
*Occ_Skyrim_AnniversaryFreeCC.esp
*Cathedral - 3D Mountain Flowers.esp
*Lux - Master plugin.esm
*Heels Sound.esm
*Smooth Weapon.esm
*TrueHUD.esl
*DynDOLOD.esm
*SkyUI_SE.esp
*Better_Male_Presets.esp
*Immersive Sounds - Compendium.esp
*Obsidian Weathers.esp
*SMIM-SE-Merged-All.esp
*Better Dynamic Snow SE.esp
*MCMHelper.esp
*UIExtensions.esp
*icepenguinworldmapclassic.esp
*RaceMenu.esp
*RaceMenuPlugin.esp
*Weapons Armor Clothing & Clutter Fixes.esp
*Modpocalypse NPCs (v2) SSE.esp
*SkyrimIsWindy.esp
*WindyGrass.esp
*fixLOD.esp
*3BBB.esp
*SOSPhysicsManager.esp
*SOSRaceMenu.esp
*XPMSE.esp
*CommunityOverlays1_0T30.esp
*autoBodyAE.esp
*HIMBO.esp
*RaceMenuMorphsHIMBO.esp
*SOS - Smurf Average Addon.esp
*SOS - VectorPlexus Muscular Addon.esp
*SOS - VectorPlexus Regular Addon.esp
*FleshFX.esp
*WeightOV - Balance - MERGED.esp
*SparklesSE.esp
*Unique Uniques.esp
*Unique Uniques_WACCF_Patch.esp
*LockRelatedLoot.esp
*FNIS.esp
*Valravn - Integrated Combat of Skyrim.esp
*WeightOV - Optional - Gold001.esp
*WeightOV - Optional - Lockpick.esp
*Dynamic Things Alternative.esp
*sweepingOrganizesStuff.esp
*[xPatch] Modpocalypse NPCs (v2) SSE - Weapons Armor Clothing & Clutter Fixes.esp
*SGEyebrows.esp
*Beards.esp
*SensibleBribes.esp
*Auto Unequip Ammo.esp
*Lux Orbis.esp
*Torch Brightness Radius.esp
*Landscape Fixes For Grass Mods.esp
*immersivemerchants.esp
*Relationship Dialogue Overhaul.esp
*Hunters Not Bandits.esp
*Bandit Lines Expansion.esp
*WaitYourTurn.esp
*Voidgate.esp
*Thief skills rebalance for Ordinator.esp
*AcquisitiveSoulGemMultithreaded.esp
*Orion - A Smithing Overhaul.esp
*Experience Quests Tweak.esp
*High Poly Head Vampire Fix.esp
*KSHairdosSMP.esp
*At Your Own Pace - Misc.esp
*Folkvangr - Grass and Landscape Overhaul.esp
*Bears of the North.esp
*3DNPC0.esp
*Cuyima 3DNPC - Redone.esp
*RSC 3DNPC Patch.esp
*Cathedral Dynamic Snow.esp
*Generic Grass Limiter.esp
*Rally's Nord War Horns - Unique Torygg's Horn.esp
*Rudy Nordic Pottery SSE.esp
*Serana Dialogue Edit.esp
*SleepTight.esp
*ogSplendorDragons.esp
*Craftable Torches.esp
*DustEffectsSSE.esp
*Gems As They Should Be.esp
*HPP - Vaermina's Torpor.esp
*pauseMenuAfterLoading.esp
*BikiniRobesStandalone.esp
*[COCO] Scarlet Rose.esp
*TrueDirectionalMovement.esp
*TKDodge.esp
*BetterThirdPersonSelection.esp
*AI Overhaul.esp
*BeastHHBB.esp
*Project ja-Kha'jay- Khajiit Diversity.esp
*BBs Whiterun Hold Male NPCS.esp
*Vanilla Hair Replacer - VHR.esp
*Lux Via - plugin.esp
*AlternatePerspective.esp
*RSChildren.esp
*[xPatch] Modpocalypse NPCs (v2) SSE - AlternatePerspective.esp
*At Your Own Pace - Thieves Guild.esp
*EconomyOverhaulandSpeechcraftImprovements.esp
*Eli_Breezehome.esp
*Odin - Skyrim Magic Overhaul.esp
*TransmuteOreSanely.esp
*Immersive Encounters.esp
*TavernAIFix.esp
*TimingIsEverything.esp
*Particle Patch for ENB.esp
*EconomyOverhaulCellsandWorldspacesEditsAddon.esp
*WACCF_Armor and Clothing Extension.esp
*CBBE.esp
*RaceMenuMorphsCBBE.esp
*Schlongs of Skyrim.esp
*fallentreebridgesSSE.esp
*Immersive Patrols II.esp
*Lux Orbis - 3DNPC patch.esp
*Realistic Humanoid Movement Speed SSE.esp
*EconomyOverhaul CV - WACCF Patch.esp
*Better Stealth AI for Followers.esp
*MisterBs Lootable Things.esp
*Lootable Things x Dynamic Things Alternative.esp
*[xPatch] Modpocalypse NPCs (v2) SSE - WACCF_Armor and Clothing Extension.esp
*Modpocalypse NPCs (v2) Immersive Patrols SE.esp
*BBs Lasses of Skyrim Redux.esp
*BBs Thieves Full NPC Replacer - High Poly.esp
*BBs Companions Full.esp
*No Vendor Spell Tomes - All Merged.esp
*At Your Own Pace - College of Winterhold.esp
*CiceroFemaleSE.esp
*CiceroFemaleConversion.esp
*At Your Own Pace - Dark Brotherhood.esp
*At Your Own Pace - Main Quest.esp
*ImprovedCompanionsBoogaloo.esp
*ICLydia_USSEP_Patch.esp
*ICLydiaRDOPatch.esp
*ICLydia_BBsLassesPatch.esp
*Immersive Encounters - RS Children Patch.esp
*RaggedFlagonSign.esp
*KrittaKittyHorsesForSSE.esp
*Andromeda - Unique Standing Stones of Skyrim.esp
*LovelyLetter.esp
*DibellaStatuesFixes.esp
*Lux Orbis - Saints and Seducers patch.esp
*The Paarthurnax Dilemma.esp
*Skyrim Flora Overhaul.esp
*Lux Orbis - USSEP patch.esp
*BentPines.esp
*[pPatch] Bentpines_Navmesh.esp
*CrestysDistantMists.esp
*CrestysDistantMists_ObisidanWeathers_Patch.esp
*VolumeticMistsSolstheim.esp
*Regreses Star Cloth.esp
*Landscape and Water Fixes - Patch - LFfGM.esp
*fallenbridgesSSE-Patch.esp
*JS Armored Circlets SE.esp
*HPP - FirewoodSnow.esp
*NewStatueOfShalidorMagicLights.esp
*Skyland Imperial Forts and Dungeons.esp
*Eli_Battle Mage Armour.esp
*VolumeticMists.esp
*Spellforge.esp
*Spellforge - Library - Base - Odin.esp
*Spellforge - Library - Odin.esp
*Ordinator - Perks of Skyrim.esp
*Ordinator_WACCF_Patch.esp
*Ordinator - Apply Spell Conditions Fix.esp
*Apocalypse - Magic of Skyrim.esp
*Apocalypse - Ordinator Compatibility Patch.esp
*Spellforge - Library - Apocalypse.esp
*Odin - Ordinator Compatibility Patch.esp
*EconomyOverhaul CV - Ordinator Patch.esp
*nwsFollowerFramework.esp
*Lux.esp
*Lux - 3DNPC patch.esp
*Lux - Alternate Perspective.esp
*Lux - RWT Patch.esp
*Lux - No grass in caves patch.esp
*Lux - Saints and Seducers patch.esp
*Lux - SLaWF patch.esp
*Lux - USSEP patch.esp
*Lux - nwsFollowerFramework Patch.esp
*Eli_Breezehome [PATCH - Lux].esp
*RealisticWaterTwo.esp
*RealisticWaterTwo - Alt Volcanic Watercolor.esp
*Skyland Watercolor - Slow Green-RW2.esp
*WACCF_BashedPatchLvlListFix.esp
*NoGrassINCaves.esp
*Bashed Patch, 0.esp
*DynDOLOD.esp
*Occlusion.esp
```

**Comment by doxxx** [comment]
If I disable all the other mods and just enable an NPC mod (like BB's Lasses of Skyrim) and AI Overhaul, along with their dependencies, then the patcher works again. So the problem is somewhere in my load order, I guess.

**Comment by Excinerus** [comment]
As the log says ; you have a missing master, one of the plugins selected has ccBGSSSE001-Fish.esm as a master and that file isn't enabled in your load order  (it doesn't figure in your plugins.txt) . the File may be missing.

**Comment by doxxx** [comment]
Thanks for the reply. Here's the thing though: It's a DLC master. I _can't_ disable it. And MO2 doesn't indicate that any of the plugins in my load order have missing masters. So I don't understand how this error could even occur.

I'm going through my load order to find which plugins use this master and to see which one is triggering the problem.

**Comment by doxxx** [comment]
Here it is enabled in my load order:

![image](https://user-images.githubusercontent.com/677940/167124170-f6a784b1-6225-4f23-9707-b26ddaf4100d.png)

**Comment by doxxx** [comment]
I only have two plugins in my load order with `ccBGSSSE001-Fish.esm` as a master:

1. Occ_Skyrim_AnniversaryFreeCC.esp
2. AI Overhaul.esp

The patcher error no longer occurs when I disable `Occ_Skyrim_AnniversaryFreeCC.esp` from [`eFPS - Anniversary Edition`](https://www.nexusmods.com/skyrimspecialedition/mods/58727). What's bothering me though is that when I first ran the patcher successfully yesterday, _I had that plugin enabled_. I've had that mod installed and enabled for weeks.

I've double-checked and the `ccBGSSSE001-Fish.esm` file exists in my Data folder.

I really think there's a problem in the patcher here. Could you take another look?

**Comment by doxxx** [comment]
Actually, I don't think it's related to either of those plugins.

I just had the patcher fail when I had `Occ_Skyrim_AnniversaryFreeCC.esp` disabled, even though it had just succeeded a few minutes before while I was writing the post above. After running the patcher again a few times with `Occ_Skyrim_AnniversaryFreeCC.esp` enabled, the patcher succeeded.

So it must be a race condition. Maybe somewhere in the code that handles the list of loaded plugins?
